name: AndroidBuild
on:
  pull_request:
    branches: [ workflow_build ]
  push:
    branches: [ workflow_build ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: SonarCloud Scan
        run: ./gradlew app:sonarqube -Dsonar.login=${{secrets.SONAR_TOKEN}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}