name: AndroidBuild
on:
  pull_request:
    branches: [ workflow_build ]
  push:
    branches: [ workflow_build ]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: SonarCloud Scan
        run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}